- name: INSTALL SQL DATABASE
  ansible.builtin.package:
    name:
      - databases/mariadb106-server
      - databases/py-pymysql
    state: present

- name: ENABLE & START MYSQL SERVICE
  ansible.builtin.service:
    name: mysql-server
    state: started
    enabled: true

- name: MARIADB OPENSTACK CONFIGURATION
  ansible.builtin.template:
    src: ./usr/local/etc/mysql/conf.d/99-openstack.cnf
    dest: /usr/local/etc/mysql/conf.d/99-openstack.cnf
    mode: 0644
  register: mariadb_openstack_configuration

- name: RESTART MYSQL SERVICE
  ansible.builtin.service:
    name: mysql-server
    state: restarted
  when: mariadb_openstack_configuration.changed

  # mysql_secure_installation
- name: Update MariaDB root password
  community.mysql.mysql_user:
    name: root
    host_all: true
    password: "{{ openstack_sql_root_dbpass }}"
    check_implicit_admin: true # on initial install there is no password
    login_user: root
    login_password: "{{ openstack_sql_root_dbpass }}"
    login_unix_socket: /var/run/mysql/mysql.sock

  # mysql_secure_installation
- name: Delete anonymous MySQL user
  community.mysql.mysql_user:
    name: ""
    host_all: true
    state: absent
    login_user: root
    login_password: "{{ openstack_sql_root_dbpass }}"
    login_unix_socket: /var/run/mysql/mysql.sock

  # mysql_secure_installation
- name: remove remote root
  community.mysql.mysql_query:
    query:
      - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
    login_user: root
    login_password: "{{ openstack_sql_root_dbpass }}"
    login_unix_socket: /var/run/mysql/mysql.sock

  # mysql_secure_installation
- name: Remove MySQL test database
  community.mysql.mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ openstack_sql_root_dbpass }}"
    login_unix_socket: /var/run/mysql/mysql.sock

- name: CREATE MYSQL EXPORTER USER
  community.mysql.mysql_user:
    name: exporter
    password: "exporter"
    resource_limits:
      MAX_USER_CONNECTIONS: 3
    priv:
      "*.*": "PROCESS,REPLICATION CLIENT,SLAVE MONITOR"
      "performance_schema.*": "SELECT"
      # "information_schema.*": "SELECT"
    host: "{{ item }}"
    state: present
    login_user: root
    login_password: "{{ openstack_sql_root_dbpass }}"
    login_unix_socket: /var/run/mysql/mysql.sock
  with_items:
    - unix_socket

- name: INSTALL MYSQLD EXPORTER
  ansible.builtin.package:
    name:
      - net-mgmt/mysqld_exporter
    state: present

- name: ENABLE & START MYSQLD EXPORTER SERVICE
  ansible.builtin.service:
    name: mysqld_exporter
    state: started
    enabled: true

- name: MYSQLD EXPORTER CONF FILE
  community.general.sysrc:
    name: mysqld_exporter_conffile
    value: "/usr/local/etc/.mysqld_exporter.cnf"

- name: MYSQLD EXPORTER CONFIGURATION
  ansible.builtin.template:
    src: ./usr/local/etc/.mysqld_exporter.cnf
    dest: /usr/local/etc/.mysqld_exporter.cnf
    mode: 0644
  register: mysqld_exporter_configuration

- name: ENABLE & START MYSQLD EXPORTER SERVICE
  ansible.builtin.service:
    name: mysqld_exporter
    state: restarted
  when: mysqld_exporter_configuration.changed
