- name: Base Shared
  hosts: all
  remote_user: ubuntu
  become: true
  roles:
    - base-shared

- name: Base Controller
  hosts: controllers
  remote_user: ubuntu
  become: true
  roles:
    - base-controller
