- name: INSTALL OVS
  ansible.builtin.package:
    name:
      - ovn-host
      - ovn-common
    state: present

- name: OVN SET REMOVE DATABASE
  command: "/usr/bin/ovs-vsctl set open . external-ids:ovn-remote=tcp:{{ hostvars[openstack_neutron_host]['ansible_tailscale0']['ipv4']['address'] }}:6642"
  changed_when: false

- name: OVN SET ENCAP TYPE
  command: "/usr/bin/ovs-vsctl set open . external-ids:ovn-encap-type=geneve,vxlan"
  changed_when: false

- name: OVN SET ENCAP IP
  command: "/usr/bin/ovs-vsctl set open . external-ids:ovn-encap-ip={{ ansible_default_ipv4.address }}"
  changed_when: false

- name: OVN ENABLE CASSIS AS GATEWAY
  command: "/usr/bin/ovs-vsctl set open . external-ids:ovn-cms-options=enable-chassis-as-gw"
  changed_when: false

- name: OVS create maanger
  command: "/usr/bin/ovs-vsctl --id @manager create Manager target='ptcp\\:6640\\:127.0.0.1' -- add Open_vSwitch . manager_options @manager"
  changed_when: false
  failed_when: false

# For some reason when adding/removing floating IPs the neutron server errors with this
#
# 2023-02-23 03:30:05.842 25044 INFO neutron.plugins.ml2.drivers.ovn.mech_driver.mech_driver [None req-accc7595-320b-47e4-93e4-b07f6b205295 - - - - - -] Refusing to bind port 5266e0cd-1064-4baa-9679-8c5f2eb13d29 on host sora due to the OVN chassis bridge mapping physical networks [] not supporting physical network: provider
# 2023-02-23 03:30:05.843 25044 ERROR neutron.plugins.ml2.managers [None req-accc7595-320b-47e4-93e4-b07f6b205295 - - - - - -] Failed to bind port 5266e0cd-1064-4baa-9679-8c5f2eb13d29 on host sora for vnic_type normal using segments [{'id': '5621a693-771d-4a57-beb4-d7a6e8dfc1b9', 'network_type': 'flat', 'physical_network': 'provider', 'segmentation_id': None, 'network_id': '71cbb38e-dc91-4db4-9a3a-7e499cd3fd69'}]
#
# This does not prevent the add/remove nor does it prevent it from working
# I think it is related to a similar issue found here https://bugs.launchpad.net/charm-ovn-chassis/+bug/1883244 but I don't understand the actual fix
# Looking in the code here https://github.com/openstack/neutron/blob/stable/zed/neutron/plugins/ml2/drivers/ovn/mech_driver/ovsdb/impl_idl_ovn.py#L850
# shows it just looks at the bridge mappings in ovn (ovn-sbctl find Chassis hostname=sora), which is correctly set to ovn-bridge-mappings="provider:br-provider" so I am unsure why this is erroring
# This is where the error is https://github.com/openstack/neutron/blob/stable/zed/neutron/plugins/ml2/drivers/ovn/mech_driver/mech_driver.py#L1004

- name: OVS PROVIDER BRIDGE
  command: "/usr/bin/ovs-vsctl --may-exist add-br br-provider -- set bridge br-provider protocols=OpenFlow13"
  changed_when: false

- name: OVS PROVIDER MAPPING
  command: "/usr/bin/ovs-vsctl set open . external-ids:ovn-bridge-mappings=provider:br-provider"
  changed_when: false

- name: OVS PROVIDER ADD PORT
  command: "/usr/bin/ovs-vsctl --may-exist add-port br-provider veth1-provider"
  changed_when: false

- name: INSTALL neutron
  ansible.builtin.package:
    name:
      - neutron-ovn-metadata-agent
    state: present

- name: neutron CONFIGURATION
  ansible.builtin.template:
    src: ./etc/neutron/neutron.conf
    dest: /etc/neutron/neutron.conf
    owner: root
    group: neutron
    mode: 0640
  register: neutron_configuration

- name: ovn metadata agent CONFIGURATION
  ansible.builtin.template:
    src: ./etc/neutron/neutron_ovn_metadata_agent.ini
    dest: /etc/neutron/neutron_ovn_metadata_agent.ini
    owner: root
    group: neutron
    mode: 0640
  register: ovn_metadata_configuration

- name: Restart neutron for configuration change
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
  when: neutron_configuration.changed or ovn_metadata_configuration.changed
  with_items:
    - neutron-ovn-metadata-agent
