- name: INSTALL CINDER
  ansible.builtin.package:
    name:
      - cinder-volume
    state: present

- name: CINDER VOLUME SYSTEMD OVERRIDE DIRECTORY
  ansible.builtin.file:
    path: /etc/systemd/system/cinder-volume.service.d
    state: directory

- name: CINDER VOLUME SYSTEMD OVERRIDE
  ansible.builtin.template:
    src: ./etc/systemd/system/cinder-volume.service.d/env.conf
    dest: /etc/systemd/system/cinder-volume.service.d/env.conf
    owner: root
    group: root
    mode: 0644
  register: cinder_volume_systemd_override_configuration

- name: DAEMON RELOAD SYSTEM FOR CINDER VOLUME OVERRIDE
  ansible.builtin.systemd:
    daemon_reload: true
  when: cinder_volume_systemd_override_configuration.changed

- name: CINDER CONFIGURATION
  ansible.builtin.template:
    src: ./etc/cinder/cinder-volume.conf
    dest: /etc/cinder/cinder-volume.conf
    owner: root
    group: cinder
    mode: 0640
  register: cinder_volume_configuration

- name: CINDER NFS SHARES
  ansible.builtin.template:
    src: ./etc/cinder/nfs_shares
    dest: /etc/cinder/nfs_shares
    owner: root
    group: cinder
    mode: 0640
  register: cinder_nfs_shares_configuration

- name: Restart Cinder Volume for configuration change
  ansible.builtin.systemd:
    name: cinder-volume
    state: restarted
  when: cinder_volume_configuration.changed or cinder_nfs_shares_configuration.changed
