- name: INSTALL nova
  ansible.builtin.package:
    name:
      - nova-compute
    state: present

- name: NOVA CONFIGURATION
  ansible.builtin.template:
    src: ./etc/nova/nova.conf
    dest: /etc/nova/nova.conf
    owner: root
    group: nova
    mode: 0640
  register: nova_configuration

- name: Restart Nova for configuration change
  ansible.builtin.systemd:
    name: nova-compute
    state: restarted
  when: nova_configuration.changed
