- name: INSTALL UTILS UBUNTU
  ansible.builtin.package:
    name:
      - htop
      - glances
      - acl
      - net-tools
      - curl
      - git
    state: present

- name: UBUNTU CLOUD KEYRING
  ansible.builtin.package:
    name: ubuntu-cloud-keyring
    state: present

- name: INSTALL OPENSTACK REPO
  ansible.builtin.apt_repository:
    repo: deb http://ubuntu-cloud.archive.canonical.com/ubuntu noble-updates/dalmatian main
