# {{ ansible_managed }}
# generated 2025-02-22, Mozilla Guideline v5.7, Apache 2.4.60, OpenSSL 3.4.0, modern config
# https://ssl-config.mozilla.org/#server=apache&version=2.4.60&config=modern&openssl=3.4.0&guideline=5.7

# Internal VHost
# Using an internal port with SSL MTLS configuration
# We can just pass-through the headers from HAProxy
# But no validation is done on the CA so we cannot do that
# Instead we are making a new port that clients will be
# able to connect through consul, https://openstack-keystone.service.consul:5200
Listen 5200
<VirtualHost *:5200>
    WSGIScriptAlias / /usr/local/bin/keystone-wsgi-internal
    WSGIDaemonProcess keystone-internal processes=5 threads=1 user=keystone group=keystone display-name=%{GROUP}
    WSGIProcessGroup keystone-internal
    WSGIApplicationGroup %{GLOBAL}
    WSGIPassAuthorization On
    LimitRequestBody 114688

    <IfVersion >= 2.4>
      ErrorLogFormat "%{cu}t %M"
    </IfVersion>

    ErrorLog /var/log/apache2/keystone-internal.log
    CustomLog /var/log/apache2/keystone-internal_access.log combined

    <Directory /usr/local/bin/>
        <IfVersion >= 2.4>
            Require all granted
        </IfVersion>
        <IfVersion < 2.4>
            Order allow,deny
            Allow from all
        </IfVersion>
    </Directory>

    SSLEngine on
    SSLCertificateFile      /etc/keystone/keystone-internal.crt
    SSLCertificateKeyFile   /etc/keystone/keystone-internal.key

    # MTLS configuration
    SSLCACertificateFile    /etc/keystone/keystone-internal-ca.crt
    SSLOptions              +StdEnvVars
    SSLVerifyClient         require
    SSLVerifyDepth          2

    # enable HTTP/2, if available
    Protocols h2 http/1.1

    # HTTP Strict Transport Security (mod_headers is required) (63072000 seconds)
    Header always set Strict-Transport-Security "max-age=63072000"
</VirtualHost>

# Public VHost
Listen 5000
<VirtualHost *:5000>
    WSGIScriptAlias / /usr/bin/keystone-wsgi-public
    WSGIDaemonProcess keystone-public processes=5 threads=1 user=keystone group=keystone display-name=%{GROUP}
    WSGIProcessGroup keystone-public
    WSGIApplicationGroup %{GLOBAL}
    WSGIPassAuthorization On
    LimitRequestBody 114688

    <IfVersion >= 2.4>
      ErrorLogFormat "%{cu}t %M"
    </IfVersion>

    ErrorLog /var/log/apache2/keystone.log
    CustomLog /var/log/apache2/keystone_access.log combined

    <Directory /usr/bin>
        <IfVersion >= 2.4>
            Require all granted
        </IfVersion>
        <IfVersion < 2.4>
            Order allow,deny
            Allow from all
        </IfVersion>
    </Directory>

    SSLEngine on
    SSLCertificateFile      /etc/keystone/keystone-public.crt
    SSLCertificateKeyFile   /etc/keystone/keystone-public.key

    # enable HTTP/2, if available
    Protocols h2 http/1.1

    # HTTP Strict Transport Security (mod_headers is required) (63072000 seconds)
    Header always set Strict-Transport-Security "max-age=63072000"
</VirtualHost>

# Alias /identity /usr/bin/keystone-wsgi-public
# <Location /identity>
#     SetHandler wsgi-script
#     Options +ExecCGI

#     WSGIProcessGroup keystone-public
#     WSGIApplicationGroup %{GLOBAL}
#     WSGIPassAuthorization On
# </Location>
# <Location /identity>
#     SetHandler wsgi-script
#     Options +ExecCGI

#     WSGIProcessGroup keystone-internal
#     WSGIApplicationGroup %{GLOBAL}
#     WSGIPassAuthorization On
# </Location>

# modern configuration
SSLProtocol             -all +TLSv1.3
SSLOpenSSLConfCmd       Curves X25519:prime256v1:secp384r1
SSLHonorCipherOrder     off
SSLSessionTickets       off

SSLUseStapling On
SSLStaplingCache "shmcb:logs/ssl_stapling(32768)"