- name: INSTALL MESSAGE QUEUE
  ansible.builtin.package:
    name:
      - net/rabbitmq
    state: present

- name: ENABLE & START rabbitmq SERVICE
  ansible.builtin.service:
    name: rabbitmq
    state: started
    enabled: true

# This is so ansible can run rabbitmq commands
- name: COPY ERLANG COOKIE TO ROOT
  ansible.builtin.copy:
    remote_src: true
    src: /var/db/rabbitmq/.erlang.cookie
    dest: /root/.erlang.cookie
    owner: root
    group: wheel
    mode: "0400"

- name: REMOVE GUEST USER
  community.rabbitmq.rabbitmq_user:
    user: guest
    state: absent

- name: CREATE ROOT USER
  community.rabbitmq.rabbitmq_user:
    user: root
    password: "{{ openstack_rabbit_root_pass }}"
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    tags: "administrator"
    state: present

- name: CREATE OPENSTACK USER
  community.rabbitmq.rabbitmq_user:
    user: openstack
    password: "{{ openstack_rabbit_pass }}"
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present

- name: ENABLE PLUGINS
  community.rabbitmq.rabbitmq_plugin:
    names: rabbitmq_management,rabbitmq_prometheus
    state: enabled
